services:      
      
  sender:
    image: sender
    build: ./sender
    env_file: ./sender/.env
    container_name: sender    
    ports:
      - '3333:3333'
      - '4444:4444' 
    networks:
      - banknet
      
      
  receiver:
    image: receiver
    build: ./receiver
    env_file: ./receiver/.env
    container_name: receiver    
    ports:
      - '5555:5555'
      - '7778:7778' 
    networks:
      - banknet
      

networks:
  banknet:
    external: true
