services:      
      
  sender:
    image: sender
    build: ./sender
    env_file: ./sender/.env
    container_name: sender    
    ports:
      - '3333:3333'
      - '4444:4444' 
    networks:
      - banknet
      

networks:
  banknet:
    external: true